import {Button} from "./components/button/button";
import {Switch} from "./components/switch/switch";
import {TextInput} from "./components/text-input/text-input";
import {Divider} from "./components/divider/divider";
import {Slider} from "./components/slider/slider";

// @ts-ignore
window.GC = {
	// @ts-ignore: GC_MINIFIED_CSS is getting generated by the build process
	styles: GC_MINIFIED_CSS,
	Button,
	Switch,
	TextInput,
	Divider,
	Slider
}
